apiVersion: batch/v1
kind: Job
metadata:
  name: premium
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: premium
        image: hieungo91/mp3-cloud-computing-applications:latest
        env:
        - name: DATASET
          value: "kmnist"
        - name: TYPE
          value: "cnv"
      restartPolicy: Never
  backoffLimit: 4