# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: test-mysql
    ports:
      - 3306:3306
    volumes:
      - /Users/cngo/dev/cs498_cloud_computing_applications/mp9/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8888:8080